on: 
    push:
    pull_request:
        branches:
            - main
    
jobs:
    hello-world:
        name: Hello World
        runs-on: ubuntu-slim
        steps:
            - run: echo "Hello World!"
    job2:
        runs-on: ubuntu-slim
        if: ${{ github.event_name == 'push' }}
        needs: hello-world
        steps:
            - uses: actions/checkout@v7
            - run: ls
    job3:
        runs-on: ubuntu-slim
        if: ${{ github.event_name == 'pull_request' }}
        steps:
            - uses: actions/checkout@v7
            - run: ls

    job4:
        runs-on: ubuntu-slim
        needs: job2
        steps:
            - uses: actions/checkout@v7
            - run: ls

    job5:
        runs-on: ubuntu-slim
        needs: [hello-world, job3]
        steps:
            - uses: actions/checkout@v7
            - run: ls